version: '3'
services:
    mongodb:
        restart: always
        container_name: mongodb
        build:
            context: ./
            dockerfile: ./.docker/mongodb.docker
        volumes:
            - "${MONGODB_PATH}:/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        ports:
            - "27017:27017"
        command: --auth

    server:
        restart: always
        container_name: server
        tty: true
        volumes:
            - "./:/root/cloud"
        build:
            context: ./
            dockerfile: ./.docker/server.docker
        ports:
          - "${HOST_PORT}:${HOST_PORT}"

    listen_module:
        restart: always
        container_name: listen_module
        tty: true
        volumes:
            - "./:/root/cloud"
        build:
            context: ./
            dockerfile: ./.docker/listen_module.docker
        links:
        - rq-server:db

#    crontab_module:
#        restart: always
#        container_name: crontab_module
#        tty: true
#        volumes:
#            - "./:/root/cloud"
#        build:
#            context: ./
#            dockerfile: ./.docker/crontab_module.docker

    rq-server:
        restart: always
        container_name: rq-server
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        build:
            context: ./
            dockerfile: ./.docker/rq-server.docker
        ports:
            - "6379:6379"

    rq-dashboard:
        restart: always
        container_name: rq-dashboard
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        build:
            context: ./
            dockerfile: ./.docker/rq-dashboard.docker
        ports:
            - "9181:9181"
        links:
            - rq-server:db

    rq-worker:
        restart: always
        volumes:
            - "./:/root/cloud"
        build:
            context: ./
            dockerfile: ./.docker/rq-worker.docker
        links:
            - rq-server:db

        command: rq worker -c utils.settings
